name: Test

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        db:
          - {name: postgres}
          # - {name: mysql, version: 8}
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: Start Database
      run: |
        env $(cat ".env.${{ matrix.db.name }}" | xargs) docker compose -f "docker-compose.${{ matrix.db.name }}.yml" up -d
    - name: Run Tests
      run: env $(cat ".env.${{ matrix.db.name }}" | xargs) go test -cover ./...
