name: Test

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        db:
          - {name: postgres, version: 16}
          # - {name: mysql, version: 8}
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: Start Database
      run: |
        docker run --detach --env-file ".env.${{ matrix.db.name }}" "${{ matrix.db.name }}:${{ matrix.db.version }}"
    - name: Run Tests
      run: env $(cat ".env.${{ matrix.db.name }}" | xargs) go test -cover ./...
