name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v3
    - name: Setup Docker Compose Stack
      run: docker compose up --detach
    - name: Run Tests
      run: docker exec bolt go test -cover ./...
