name: Test

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  run-tests:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        db:
          - {name: postgresql}
          - {name: mysql}
          - {name: mssql}
          - {name: sqlite3}
    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
    - name: Start Database
      if: matrix.db.name != 'sqlite3'
      run: |
        env $(cat ".env.${{ matrix.db.name }}" | xargs) docker compose -f "docker-compose.${{ matrix.db.name }}.yml" up -d
    - name: Run Tests
      run: env $(cat ".env.${{ matrix.db.name }}" | xargs) go test -tags "${{ matrix.db.name }}" -cover ./...
